nginx:
    image: nginx:stable
    ports:
        #- "80:80"
        #- "443:443"
        - "443:443"
    volumes:
        - ./appui/:/usr/share/nginx/html/myapp
        - ../ui/conf/nginx.conf:/etc/nginx/nginx.conf
        - ../ui/conf/certs:/etc/nginx/certs
        #- ../ui/conf/conf.d:/etc/nginx/conf.d
        - ./appui/conf/conf.d/myapp.conf.docker:/etc/nginx/conf.d/myapp.conf
        - ./appui/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ../ui/conf/conf.d/gzip.conf:/etc/nginx/conf.d/gzip.conf
        - ../ui/conf/conf.d/location_params:/etc/nginx/conf.d/location_params
    extra_hosts:
        - "chost:172.20.123.1"
    links:
        - myappapp
myappapp:
    build: app
    ports:
        - "7100:7100"
    volumes:
        - ./app:/opt/company/myapp/app
        - ./app/conf/app.yml.docker:/opt/company/myapp/app/conf/app.yml
        - ./app/conf/api.p12:/opt/company/myapp/app/conf/api.p12
        - ./app/conf/us_zip_lat_long.csv:/opt/company/myapp/app/conf/us_zip_lat_long.csv
        # - ./app/conf:/opt/company/myapp/app/conf
        - ./app/src/main/scripts:/opt/company/myapp/scripts
        - /etc/resolv.conf:/etc/resolv.conf
    working_dir: /opt/company/myapp/app
    links:
        - mongodb
    privileged: true
    entrypoint: sh -c 'sleep 3 && /opt/company/myapp/app/devstart.sh'
mongodb:
    image: mongo:3.0
    volumes:
        - ./docker-volumes/mongodb/db:/data/db
        - ./docker-volumes/mongodb/configdb:/data/configdb
